In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [4]:
df.sample(5)

    age  gender   review education purchased
49   25  Female     Good        UG        No
4    16  Female  Average        UG        No
15   75    Male     Poor        UG        No
45   61    Male     Poor        PG       Yes
3    72  Female     Good        PG        No

In [5]:
df = df.iloc[:,2:]

In [6]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [7]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size = 0.2)

In [8]:
y_train

46     No
12     No
24    Yes
1      No
16    Yes
25     No
47    Yes
13     No
10    Yes
2      No
4      No
40     No
19    Yes
45    Yes
7     Yes
5     Yes
28     No
32    Yes
35    Yes
37    Yes
9     Yes
0      No
41    Yes
43     No
15     No
8      No
11    Yes
48    Yes
18     No
22    Yes
17    Yes
39     No
26     No
42    Yes
23     No
38     No
30     No
6      No
44     No
21     No
Name: purchased, dtype: object

## OrdinalEncoder

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
X_train

     review education
46     Poor        PG
12     Poor    School
24  Average        PG
1      Poor        UG
16     Poor        UG
25     Good    School
47     Good        PG
13  Average    School
10     Good        UG
2      Good        PG
4   Average        UG
40     Good    School
19     Poor        PG
45     Poor        PG
7      Poor    School
5   Average    School
28     Poor    School
32  Average        UG
35     Poor    School
37  Average        PG
9      Good        UG
0   Average    School
41     Good        PG
43     Poor        PG
15     Poor        UG
8   Average        UG
11     Good        UG
48     Good        UG
18     Good    School
22     Poor        PG
17     Poor        UG
39     Poor        PG
26     Poor        PG
42     Good        PG
23     Good    School
38     Good    School
30  Average        UG
6      Good    School
44  Average        UG
21  Average        PG

In [11]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [12]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [13]:
X_train = oe.transform(X_train)

In [14]:
X_train

array([[0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [1., 2.]])

## Label Encoder

In [15]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [18]:
le.fit(y_train)

LabelEncoder()

In [19]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [20]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [21]:
y_train

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## hot one encoding  for nominal data using pandas

In [22]:
cars = pd.read_csv('cars.csv')
cars.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [23]:
cars['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [24]:
pd.get_dummies(cars,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [25]:
pd.get_dummies(cars,columns=['fuel','owner'],drop_first=True)   # remove first column of each category to remove multicolinearity

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## hot one encoder using column transformer

In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [71]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [72]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [73]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [74]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

X_train_fever = si.fit_transform(X_test[['fever']])

(20, 1)

In [59]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

X_test_cough = oe.fit_transform(X_test[['cough']])

X_test_fever

In [60]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [61]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder( sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [62]:
transformer.fit_transform(X_train).shape

(80, 7)

In [ ]:
# here we encode the data and the now the data shape is (80,7) where 7 columns is  [age male fevel cought  Kolkata  Bangalore Delhi ]